### ISSUE TITLE
LWT Topic is wrong (off by one?)

### ISSUE THREAD

**Issue by toke** [marvinroger/homie-esp8266#101]
Affected Version v1.5.0 

## Problem

The last will topic is missing the last character `…/$online` -> `$onlin`

```
homie/devices/bb1/$online true
homie/devices/bb1/$nodes temperature:temperature,heatindex:heatindex,humidity:humidity
…
homie/devices/bb1/heatindex/degrees 27.38
homie/devices/bb1/$onlin false
```

## Expected result

The LWT should be complete `…/$online`

## How to reproduce

Using a arbitary sketch and compare the the LWT on boot and on connection loss.

Library version PubSubClient v2.6

## Notes

I've looked some minutes into it and tried to add a character on src/Homie/Boot/BootNormal.cpp:85 
`this->_fillMqttTopic(PSTR("/$online"));` like `  this->_fillMqttTopic(PSTR("/$onlineX"));` and it "solved" that issue in a way.

**Comment by toke** [comment]
The problem seems to be related to something with platformio.
If I'm not too tired it works with the Arduino IDE.

**Comment by marvinroger** [comment]
This is a weird one... To be honest, I am not using pio, but I don't see how this can happen.

**Comment by marvinroger** [comment]
Anyway, v2.0.0 does not use the same MQTT implementation, and I just tested and it works perfectly. We'll then see if this happen again.

**Comment by marvinroger** [comment]
I can't see this behavior, please reopen if you have an issue with the upcoming release.
