### ISSUE TITLE
64 hexadecimal WPA2-PSK password support

### ISSUE THREAD

**Issue by peterhanzlik** [marvinroger/homie-esp8266#102]
If trying to input 64 hexadecimal digit WPA2-PSK password, Homie reports following error on Serial:
`Config file is not valid, reason: wifi.password is too long`

64 hexadecimal WPA password is valid:
> "This key may be entered either as a string of 64 hexadecimal digits, or as a passphrase of 8 to 63 printable ASCII characters." (https://en.wikipedia.org/wiki/Wi-Fi_Protected_Access#WPA_terminology)

**Comment by marvinroger** [comment]
Thanks for the information, it's only a matter of changing a constant, but v2.0.0 won't be released very soon as it relies on some feature not even released on the stable channel of esp8266/Arduino.
