### ISSUE TITLE
use standard ArduinoOTA

### ISSUE THREAD

**Issue by lighthousebulb** [marvinroger/homie-esp8266#109]
I do have a question:
Is it possible to use the old standard Arduino-OTA-Method somehow?

I have done a
`#include <ArduinoOTA.h>`
and use a 
`ArduinoOTA.handle();` inside a homie-LoopFunction,
but the node is not responding from within platform-io's OTA Upload-Method.
I looks like homie overwrites ArduinoOTA.

It would be very handy, during development to have the standard Arduino-OTA-Method from within platform-io.

Any suggestions?

**Comment by lighthousebulb** [comment]
Awesome! Got it working...
Thanks for reading my question, but you can close this ;-)

You need to send something to the $ota-Topic first and then the node responses to a platform-io-OTA-request as well.

**Comment by marvinroger** [comment]
Glad you got it working!
