### ISSUE TITLE
MQTT not working if more than 4 subscriptions

### ISSUE THREAD

**Issue by enavarro222** [marvinroger/homie-esp8266#11]
I got `Homie.sendProperty` that returns false (even if some time msg is sent) and some random MQTT reconnection when I get more than 4 `Homie.addSubscription`.

It seems to be linked to https://github.com/knolleary/pubsubclient/issues/98

Maybe one should add a `mqtt.loop` call in `Homie.addSubscription` ?

**Comment by marvinroger** [comment]
Yes this is probably the issue. We need to add `mqtt.loop()` after https://github.com/marvinroger/homie-esp8266/blob/master/src/Homie/Boot/BootNormal.cpp#L99

I will fix tomorrow!

**Comment by marvinroger** [comment]
Can you try again?

**Comment by enavarro222** [comment]
Thanks, I'll test it tonight.

**Comment by enavarro222** [comment]
OK you can close it, the fix works.

**Comment by enavarro222** [comment]
Oh I didn't take care: I can close it myself...
