### ISSUE TITLE
ESP 1MB vs 4MB

### ISSUE THREAD

**Issue by peterhanzlik** [marvinroger/homie-esp8266#114]
Hello Marvin,

I would like to ask whether there is any difference in using Homie on ESP 1MB vs 4MB flash size, in terms of set of features (OTA), stability or any other aspects.

Thank you
Peter

**Comment by marvinroger** [comment]
Yes, OTA is not available when using 1MB of flash size. I'm not 100% sure, though. Other than that, there is no difference. :)

**Comment by peterhanzlik** [comment]
Hi Marvin, thank you for the answer.
