### ISSUE TITLE
Return type of setNodeProperty method in Homie

### ISSUE THREAD

**Issue by NigelTwo** [marvinroger/homie-esp8266#123]
In an example (DoorSensor) there is a test applied to SetNodeProperty viz.
if (Homie.setNodeProperty(doorNode, "open", doorValue ? "true" : "false", true)) {
But in the class methods, setNodeProperty is declared as void viz.
void HomieClass::setNodeProperty(
What was the intention here void or boolean?

**Comment by marvinroger** [comment]
Well you're right, the examples in the latest git revision need to be updated. The fact is the latest release (v1.5.0) is synchronous, so `setNodeProperty` returns whether it was a success or not. However, the v2.0.0 will be asynchronous, so the function cannot return immediate feedback about whether it worked or not. That is why it is now `void`.
