### ISSUE TITLE
examples in 2. Getting started

### ISSUE THREAD

**Issue by prijswij** [marvinroger/homie-esp8266#126]
I was trying the examples and could not get it to work. After some research I found it missed the following:
  `Homie.registerNode(lightNode);`

**Comment by marvinroger** [comment]
You need to use the examples bundled with your release. The ones in the latest git revision are not backward compatible with the latest v1.5.0.

**Comment by marvinroger** [comment]
I just added a clarification about this: 900f22a1a9466fa31468990d226cdb64712746f4
