### ISSUE TITLE
Property discovery

### ISSUE THREAD

**Issue by stufisher** [marvinroger/homie-esp8266#128]
It seems to me that it is possible to discover nodes from a device, but no way to discover their properties. This means that the user has to have prior knowledge of properties on a device in order to make use of them.

I'd like to automate adding properties to my database iot system and to do this sensibly i'd like to be able to discover properties. This would require properties to be registered up front like nodes are at the moment. Thoughts?

**Comment by marvinroger** [comment]
It's being discussed there: https://github.com/marvinroger/homie/issues/4, let's separate things related to the convention itself and the ESP8266 implementation.
