### ISSUE TITLE
Links not working

### ISSUE THREAD

**Issue by RudyFiero** [marvinroger/homie-esp8266#137]
•JSON configuration file to configure the credentials of the device
•Cute API / Web UI / App to remotely send the configuration to the device and get information about it
•OTA support

The links on your page (marvinroger/homie-esp8266 )  gives 404 errors.

**Comment by marvinroger** [comment]
Fixed, thanks! Beware the new links point to the v2.0.0 documentation that is not yet released. If you want the docs related to the v1.5.0, head on to https://github.com/marvinroger/homie-esp8266/tree/v1.5.0
