### ISSUE TITLE
What's different between Async and the other?

### ISSUE THREAD

**Issue by pumpindex** [marvinroger/homie-esp8266#145]
one thing is not clear for me. Whats different between async-mqtt-client library and pubsubclient.h library in mqtt exactly? also for asyncwebserver and webserver?
what is advantages and disadvantages of asynchronous in compared of synchronous in esp8266?

**Comment by marvinroger** [comment]
I am not an expert either, but think threads (it's not, actually, just a picture). A synchronous implementation runs in the main loop. So for example, to connect to a TCP socket, if it takes 3 seconds, the whole code would block for 3 seconds. An asynchronous implementation does not run in the main loop. When you will connect to the TCP socket, it will work in the background and call your code back (callback) when it's done. So it's not blocking, you can do whatever you want in between! Simply put, the advantage here it is faster and more bulletproof. You can easily crash PubSubClient under high load, nobody managed to break AsyncMqttClient yet. :wink:
