### ISSUE TITLE
Deep sleep function without interfering with the homie module functions

### ISSUE THREAD

**Issue by gubagu** [marvinroger/homie-esp8266#146]
Question:

Is it possible to use esp8266's "ESP.deepSleep(microseconds, mode)" function without interfering with the homie module functions (https://github.com/esp8266/Arduino/blob/master/doc/libraries.md#esp-specific-apis) ?

I have in mind enegy efficient sensor that lets say gets measurements publish them to the broker and goes in deepsleep again.

Furhter more i noticed that homie modules report their availability and probably to turn off that function in the energy efficient mode with deep sleep.

Thanks in advance !

Cheerz, Guby

**Comment by marvinroger** [comment]
Yes, you can use it. The upcoming version will allow you to be notified when one of your message is received by the broker. So you will only have to deep sleep when you receive the notification.

The initial sending of information is only a matter of milliseconds, whereas you need to wait a second to connect to the Wi-Fi / broker anyway, so there's no need to sacrifice this feature to gain like 30ms out of a second or two.

**Comment by luebbe** [comment]
This may also be of interest to you: [Homie and light sleep - How it is done](https://github.com/marvinroger/homie-esp8266/issues/412).
I needed a sensor that runs on batteries, consumes as little energy as possible but can be woken up by an interrupt or button press without having reboot completely.
