### ISSUE TITLE
Blocking mqtt

### ISSUE THREAD

**Issue by cingolanifede** [marvinroger/homie-esp8266#159]
Hi. Is there any way to avoid blocking the code when mqtt connection get lost and cant reconnect?
Maybe using the handler in the loop function?

**Comment by jpcacace** [comment]
hi...i 've been having the same problem....is there any way that the code doesn't block the app in the esp when the connection to the broker is lost??

**Comment by euphi** [comment]
I never tried this with the current release 1.5, but the current development version 2 (that uses a new mqtt library) does not block when connection to mqtt broker is lost.

**Comment by marvinroger** [comment]
Yes, the v1.x branch uses a sync MQTT implementations, the upcoming v2.x will fix this issue. I'll bump this topic when released.

**Comment by cingolanifede** [comment]
Thanks. Working now

**Comment by jpcacace** [comment]
Thanks!
