### ISSUE TITLE
Homie Configurator didn't go to next step

### ISSUE THREAD

**Issue by Tokandol** [marvinroger/homie-esp8266#176]
Homie configurator did not go to next step, when I checked "Use MQTT authentication".
But, if not checked, can go to next step. I tested Web UI and app, and result is same.
I couldn't find any issues about.  Now I'm testing with release 2.0.0 and using CloudMQTT broker.

![image](https://cloud.githubusercontent.com/assets/22850041/19408024/0e75f626-92ee-11e6-9918-00efbfcfda8b.png)

So I trying to debug using Chrome on PC, there are some errors below when pushed next button.
![image](https://cloud.githubusercontent.com/assets/22850041/19408014/d81b61c4-92ed-11e6-9dd2-5d8a6cc71c02.png)
![image](https://cloud.githubusercontent.com/assets/22850041/19408080/67003b66-92ef-11e6-8f57-4153d2a1a2d6.png)

**Comment by marvinroger** [comment]
It should be fixed now. Can you try again?

**Comment by Tokandol** [comment]
Thanks Marvin.

It works good. But there are problem " Invalid or too big JSON" in serial monitor.  It seems same second issue in [#178.](https://github.com/marvinroger/homie-esp8266/issues/178). 
 Below is capture of structure of data.

![image](https://cloud.githubusercontent.com/assets/22850041/19414485/980c7e64-9389-11e6-86e2-0146f92fc7e5.png)

**Comment by marvinroger** [comment]
Can you try with the latest git?

**Comment by Tokandol** [comment]
Hi Marvin

It work good without any error. But my device did not work normally. 
It repeat endlessly to connect MQTT and disconnect MQTT.  

![image](https://cloud.githubusercontent.com/assets/22850041/19425234/f2a27ce8-946a-11e6-9b5e-2f90779d7df3.png)

**Comment by Tokandol** [comment]
The reason of repetition is I have a another device using same Device Id.  So MQTT is disconnected and Homie trying to reconnect.

**Comment by marvinroger** [comment]
Great!

**Comment by alco28** [comment]
double confirmed that it works :) thanks for your effort on all! I'm just starting to learn the capabilities of an ESP8266 with your stuff!
