### ISSUE TITLE
expose find(nodeID) method public

### ISSUE THREAD

**Issue by KipK** [marvinroger/homie-esp8266#177]
Hi

Great work so far. Thanks for this project.

I'm playing with your dev branch. 
Would it be possible to expose the HomieNode* find(nodeID) method to public ? 
I'd like to get dynamically the current HomieNode in a globalInputHandler to call a setNodeProperty to the related node.

Thanks

**Comment by marvinroger** [comment]
Sure!

**Comment by marvinroger** [comment]
I changed the signature of the global input handler to:

```c++
bool globalInputHandler(const HomieNode& node, String property, HomieRange range, String value)
```

Is it fine for you?

**Comment by KipK** [comment]
Pretty nice. Thanks

**Comment by marvinroger** [comment]
You're welcome!
