### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by Gulaschcowboy** [marvinroger/homie-esp8266#179]
Hi,

is there a way to send topics with do not retain flag set? Sorry if the question is stupid.

Thanks,
Alex

**Comment by marvinroger** [comment]
```cpp
Homie.setNodeProperty(node, "property").setRetained(false).send();
```

https://homie-esp8266.readme.io/docs/cpp-api-reference#section-functions-to-call-after-homie-setup- 😉

**Comment by Gulaschcowboy** [comment]
Cool, thank you. Again, nice project, quick support!
