### ISSUE TITLE
Wrong logic when connecting to MQTT

### ISSUE THREAD

**Issue by furyfire** [marvinroger/homie-esp8266#19]
There's a bug upon connecting to an MQTT server with a username/password.

`
bool connectResult;
if (Config.get().mqtt.auth) {
  connectResult = this->_shared_interface->mqtt->connect(client_id, Config.get().mqtt.username, Config.get().mqtt.password, topic, 2, true, "false");
  } else {
    connectResult = this->_shared_interface->mqtt->connect(client_id, topic, 2, true, "false");
  }
`
Is the correct way

**Comment by marvinroger** [comment]
Oops, I'll fix!
