### ISSUE TITLE
D3 and D4 pins always HIGH

### ISSUE THREAD

**Issue by manelmg** [marvinroger/homie-esp8266#203]
Hi,
First of all, apologies for open an issue for this question, it's a question, not an issue.

I'd realised D3 and D4 pins are always HIGH and I don't know why. I want use this two pins as outputs to use nodemcu motor shield.

I think, at least one of this pins (D3?) is for reset, but I am not sure. Is is possible use both pins (D3 and D4) as user output pins?

Thanks in advance,
M

**Comment by marvinroger** [comment]
Well, this is not an `homie-esp8266` question, so I am not sure, but I guess yes, it'll work.

**Comment by benzino77** [comment]
Maybe this will help: https://forum.wemos.cc/topic/148/boot-problem-if-pins-on-gnd
