### ISSUE TITLE
version 2 is it live yet ?

### ISSUE THREAD

**Issue by leeiberry** [marvinroger/homie-esp8266#206]
just wondering if version 2 is live yet ?

reason for asking there are a few components that only work for version 2 only now and the online doco is version 2 now 

TA

Leeb

**Comment by leeiberry** [comment]
note the only way i can create/update the JSON file for a homie version 1.5 is via uploading the data file with the BIN

**Comment by marvinroger** [comment]
I understand this is not clear. I added a note in the README. See https://github.com/marvinroger/homie-esp8266#note-for-v1x-users

And yes, there's no way to update the config with the v1.5.
