### ISSUE TITLE
Changing Config After Setup

### ISSUE THREAD

**Issue by boilermanc** [marvinroger/homie-esp8266#210]
Hey Marvin, i think i am just missing it in your documentation, but how do you update the config once you have it setup? i have the wifi working and it creates an ip on my network - that was cool. but now i need to add the mqtt information. 

thanks!

**Comment by keesma** [comment]
You can send an MQTT $reset message with true to the device.
I can see the device goes back to AP mode and can connect it (Homie-xxxx).
However after I am stuck. Both the app and the webpage are stuck at "Waiting for the device".
Note am I am running v1.5 of Homie.

**Comment by marvinroger** [comment]
@boilermanc with the v2 you can update the configuration over MQTT : https://homie-esp8266.readme.io/docs/ota-configuration-updates#section-configuration-updates 😉

**Comment by marvinroger** [comment]
Feel free to reopen if needed.
