### ISSUE TITLE
suggestion: custom settings doc improvement

### ISSUE THREAD

**Issue by boneskull** [marvinroger/homie-esp8266#227]
Hi,

The documentation example [reads as follows](https://homie-esp8266.readme.io/docs/custom-settings):

```cpp

HomieSetting<long> percentageSetting("percentage", "A simple percentage");  // id, description

void setup() {
  percentageSetting.setDefaultValue(50).setValidator([] (long candidate) {
    return (candidate >= 0) && (candidate <= 100);
  });

  Homie.setup();
}
```

However, I noticed CLion will complain about this syntax:

![Parameter Type Mismatch: Types 'std::function<bool<T>' and 'bool (*)(long)' are not compatible](https://cl.ly/2P0Q3u39080H/Image%202016-11-18%20at%2017.40.45.png)

I figure others may run into this, and it may be a good idea to address it.

By casting to a `std::function` object, we can eliminate the warning:

```cpp
percentageSetting.setDefaultValue(50)
  .setValidator(std::function<bool (long)>([] (long candidate) {
    return (candidate >= 0) && (candidate <= 100);
  }));
```

* * *

Related question:

Having never used `std::function` before (knowingly), and not having touched C++ templates for over 15 years, I don't know a better way to eliminate the warning.  *Is* there any way to do this other than the above, given the definition of `setValidator()`?

**Comment by marvinroger** [comment]
Well, I am not a C++ expert either, but `std::function<bool(T)>` and `bool (*)(long)` *are* compatible, otherwise it would not even compile. So I guess it's a CLion issue (again, I may be wrong).

I learned C++ while creating this project, so I am afraid I cannot help more than that.

**Comment by boneskull** [comment]
Closing as this seems to be a CLion bug
