### ISSUE TITLE
Make the configuration AP open?

### ISSUE THREAD

**Issue by marvinroger** [marvinroger/homie-esp8266#230]
Hi everyone, 

I am considering making the configuration AP open. I think having to type a password (that is a part of the SSID) is cumbersome and does not really secure anything anyway, as the project is public and open-source.

What do you think? Please use the reaction feature of GitHub (:+1: or :-1:) to give your opinion, and don't hesitate to comment if you want to discuss it.

Thanks!

**Comment by shogsbro** [comment]
Agree; on the assumption there isn't any way an already configured Homie node will enter config state just because it cannot connect to the WiFi network it is configured to use.

**Comment by flaviostutz** [comment]
+1 on this

**Comment by cobii** [comment]
+1 (Make it configurable: default open, when a flag in firmware is set PW)

**Comment by marvinroger** [comment]
I did think about a flag, something like this:

```c++
Homie.setConfigurationApPassword("mypass");
```

I know, the function name is rather long, but I like explicit names.
And by default, the AP would not have any password. Everyone's happy! 😉

**Comment by flaviostutz** [comment]
+1 on programmable password!

**Comment by zieherf** [comment]
also +1 on the programmable password - should make everyone happy.

**Comment by marvinroger** [comment]
Done! Thanks for your feedbacks.
