### ISSUE TITLE
2 or more Pin LigthOnOff example ino

### ISSUE THREAD

**Issue by lesjaw** [marvinroger/homie-esp8266#235]
I still cant figure it out if i use the esp12 for 2 or more ON OFF light function.. can you give an ino example for 2 or more Pin that we use?

thank you

Before submitting your issue, make sure:

- [x] You're using a [stable release](https://github.com/marvinroger/homie-esp8266/releases), not the Git development version which is, by definition, unstable
- [x] You've read the documentation for *your* release, which is in the `docs/` folder of the `.zip` of the release you're using, especially the **Getting started** and **Troubleshooting** pages, which contain respectively the minimum required version of the dependencies, and some answsers to the most common problems
- [x] You're using the examples bundled in *your* release, which are in the `examples/` folder of the `.zip` of the release you're using. Examples in the latest git revision might not be backward-compatible with your release

Thanks!

**Comment by marvinroger** [comment]
The [LedStrip example](https://github.com/marvinroger/homie-esp8266/blob/develop/examples/LedStrip/LedStrip.ino) does exactly that. 😄

**Comment by lesjaw** [comment]
aah..i see it now.. damn!..thank you..will try asap
