### ISSUE TITLE
[Question] IteadSonoffButton example - use physical switch instead pushbutton

### ISSUE THREAD

**Issue by NemoN** [marvinroger/homie-esp8266#238]
I have a physical switch connected to the esp8266 module and not a pushbutton.
It is possible to toggle the connected relay on every switch change?

I tried to change the code, but i'm unable to get it working (maybe debouncing issues?)

Example workflow:

- Turn physical Switch ON (PIN HIGH) -> Toggle physical relay (ON) -> MQTT status switch "on"
- MQTT pub switch "off" -> Toggle physical relay (now OFF)
- Turn physical Switch OFF (PIN LOW) > Toggle physical relay (now ON again) -> MQTT status switch "on"

**Comment by marvinroger** [comment]
Of course it is possible! Have you had any success with a "normal" Arduino sketch, without Homie?

**Comment by NemoN** [comment]
Got this working in the meantime. Thanks to the great framework 👍
