### ISSUE TITLE
Homie v1.5 on platformio and wrong documentation

### ISSUE THREAD

**Issue by elbowz** [marvinroger/homie-esp8266#246]
Hi,

 if I follow the Getting started of documentation (https://homie-esp8266.readme.io/docs/getting-started):

* ```platformio lib install 555```

But this install the version 1.5 that don't run the bare-minimum sketch:
```
#include <Homie.h>

void setup() {
  Homie_setFirmware("bare-minimum", "1.0.0"); // The "_" is not a typo! See Magic bytes
  Homie.setup();
}

void loop() {
  Homie.loop();
}
```

edit: For solve the issue I have downloaded Homie from git (master) and edit the platformio.ini:
```
[...]
lib_deps = AsyncMqttClient, ArduinoJson, Bounce2
```

**Comment by benzino77** [comment]
You can install Homie v2 by putting this to your project properties:
```
lib_deps =  https://github.com/marvinroger/homie-esp8266.git
```

**Comment by elbowz** [comment]
Great!

**Comment by benzino77** [comment]
To tell the truth it can be mixed . Have a look here: [platformio lib_deps](http://docs.platformio.org/en/stable/projectconf.html#lib-deps)

**Comment by elbowz** [comment]
I see! I have just started to use platformio, so I don't know this feature.

Anyway, if you follow the documentation for Homie v2, you'll get error

**Comment by elbowz** [comment]
The "workaround":
```
lib_deps = Adafruit DHT Unified, https://github.com/marvinroger/homie-esp8266.git, ArduinoJson, AsyncMqttClient, Bounce2
```

**Comment by marvinroger** [comment]
Homie v2 is not yet released, so stable version is still the v1.5. The v2 docs is made as if it was already released, so that as soon as the v2 code is ready we can release it.

**Comment by elbowz** [comment]
Well, I have understand...anyway in the v2 docs is the only "mistake" I have found :+1: 

feel free to close the issue...thanks!

**Comment by marvinroger** [comment]
Yeah I know it's kind of messy.. Sorry about that. ;)
