### ISSUE TITLE
[Suggestion] Add Homie.getLogger()

### ISSUE THREAD

**Issue by elbowz** [marvinroger/homie-esp8266#248]
For what I figure out calling ```Homie.disableLogging()```, Homie don't throw debug msg, but sketch output ```Serial << "something to print out" << endl``` continue to throw.

But if we use the proposed method: ```Homie.getLogger() << "something to print out" << endl``` you can disable/enable the whole logging.

Maybe a stupid idea?!

**Comment by marvinroger** [comment]
No, that's a good idea. 😃

**Comment by elbowz** [comment]
Great!

I think also is very very simple :)

**Comment by marvinroger** [comment]
Done!
