### ISSUE TITLE
setLoopFunction gets called before the connection is active

### ISSUE THREAD

**Issue by furyfire** [marvinroger/homie-esp8266#260]
loopHandler gets called before Homie is successfully connected to the MQTT server

`bool first_time = true;
void loopHandler() {
    
    if (first_time) // New preset or station?
    {
        Serial.println("TOO SOON!");
        first_time = false;
    }    
}

void setup() {
  Serial.begin(115200);
  Serial.println();
  Serial.println();
  Homie_setBrand("FuryFire");
  Homie_setFirmware("DeskControl", "1.0.0");
 
  Homie.setLoopFunction(loopHandler);

  Homie.setup(); 
}

void loop() {
  Homie.loop();
}`

Debug output

`↕ Attempting to connect to Wi-Fi...
TOO SOON!
✔ Wi-Fi connected
Triggering WIFI_CONNECTED event...
↕ Attempting to connect to MQTT...
Sending initial information...`

Before submitting your issue, make sure:

- [X] You've read the documentation for *your* release, which is in the `docs/` folder of the `.zip` of the release you're using, especially the **Getting started** and **Troubleshooting** pages, which contain respectively the minimum required version of the dependencies, and some answsers to the most common problems
- [X] You're using a [stable release](https://github.com/marvinroger/homie-esp8266/releases), not the Git development version which is, by definition, unstable
- [X] You're using the examples bundled in *your* release, which are in the `examples/` folder of the `.zip` of the release you're using. Examples in the latest git revision might not be backward-compatible with your release

Thanks!

**Comment by flaviostutz** [comment]
I think that is expected. Is documentation wrong?
You can check it on Homie.isConnected() if you wish.

**Comment by furyfire** [comment]
> The loop function will be called everytime, when the device is in normal mode and the network connection is up. 

I understand that as it being run whenever the device is connected to the MQTT server

Considering other parts of the documentation says 

> If, for some reason, you want to run some code in the Arduino loop() function, it might be useful for you to know if the device is in configured (so in normal mode) and if the network connection is up.

I will sue Homie.isConnected() - Just a weird thing I'm fairly certain older versions of Homie did

**Comment by marvinroger** [comment]
The loop function is meant to be called only when the connection is up, so yes, there's something wrong. I'll take a look as soon as I can.

Sorry for the long response time, studies are my priority!

**Comment by elbowz** [comment]
take a look at [this commit](https://github.com/marvinroger/homie-esp8266/commit/0527756f3d19120a2b7d2ef0aa21ee8377e99b61), I had roll back and works like a charm...thanks!

**Comment by furyfire** [comment]
#290 Pull request for fix
