### ISSUE TITLE
Custom setting char * get() returns '0'

### ISSUE THREAD

**Issue by keesma** [marvinroger/homie-esp8266#279]
I am trying out the custom settings for Homie.
I have two strings and a boolean.
The boolean works fine, the string function get() returns '0'.
I can see in an MQTT monitor that the setting is correctly stored in the config.
Has anybody have a working sample of the string custom setting?

**Comment by brodtm** [comment]
I am using strings, they work ok for me;

HomieSetting<const char*> alt_ssid1("alternate_ssid1", "Alternate SSID 1");  // id, description

in setup() I have 
alt_ssid1.setDefaultValue("");

I can print the value with
Serial1 << alt_ssid1.get() << endl;

**Comment by brodtm** [comment]
My Json looks like this:
```

{"wifi":{"ssid":"XXX", "password": "xxx"},
"mqtt":{"host":"XXXX","port":1883,"base_topic":"devices/","auth":false},
"name":"XXXXX",
"ota":{"enabled":true},
"settings":{"alternate_ssid1":"XXXX","alternate_pwd1":"xxxx"}}
```

**Comment by keesma** [comment]
Thanks for the sample. It eventually helped my find my error.
I called the .get() from the setup() function. When I moved that to the setupHandler() everything works fine! Thanks again for your help.
