### ISSUE TITLE
Calling setProperty in certain conditions from Node class derived from HomieNode breaks MQTT Client

### ISSUE THREAD

**Issue by camilorodegheri** [marvinroger/homie-esp8266#285]
Hi,

I'm using the latest develop commit (7dc2dd5) and when calling setProperty from a derived class on onReadyToOperate in the following conditions is causing MQTT Client to break, before sending any packet to the server.

Tested conditions
1.  Calling it twice from the same node
`void ANode::onReadyToOperate()
{
    	setProperty("enable").send("true");
    	setProperty("enable").send("true");
}`

2. Calling from two different nodes, but using the same property name
`void BNode::onReadyToOperate()
{
    	setProperty("enable").send("true");
}`
`void CNode::onReadyToOperate()
{
    	setProperty("enable").send("true");
}
`

Is this a limitation or a bug? Or am I using it wrong? Maybe is there some issue with the way I'm referencing the function?

**Comment by marvinroger** [comment]
Please update to the latest AsyncMqttClient (v0.7.0).
