### ISSUE TITLE
MQTT $localip gets truncated

### ISSUE THREAD

**Issue by pwrsoft** [marvinroger/homie-esp8266#309]
Having an issue with Homie v2.0.0 MQTT $localip
it gets truncated in the last symbol when published in MQTT:
e.g. instead of "192.168.1.128" it gets "192.168.1.12", tested this on two nodes but with the same results.

**Comment by bertmelis** [comment]
try changing the file BootNormal.cpp on line 193:

```C++
snprintf(localIpStr, MAX_IP_STRING_LENGTH - 1, "%d.%d.%d.%d", localIp[0], localIp[1], localIp[2], localIp[3]);
```
to
```C++
snprintf(localIpStr, MAX_IP_STRING_LENGTH + 1, "%d.%d.%d.%d", localIp[0], localIp[1], localIp[2], localIp[3]);
```

**Comment by pwrsoft** [comment]
Thank you for your reply and suggestion!
Checked the solution you provide - the IP is now OK!

One thing that changed too is the device id – is gets extended by 1 symbol (for some reason):
e.g. XXXXXXXXXf9 changed to XXXXXXXXXf93

**Comment by bertmelis** [comment]
The default device ID is actually the MAC address and hence is 12 characters long. It was a bug: see #296 
The underlying cause was the same for this issue. You could propose a pull request for this solution (otherwise I will).

**Comment by pwrsoft** [comment]
Feel free to make a pull request! :+1:

**Comment by marvinroger** [comment]
Fixed with the above PR, thanks!
