### ISSUE TITLE
default values are not validated

### ISSUE THREAD

**Issue by boneskull** [marvinroger/homie-esp8266#324]
If doing this:

```cpp
  mySetting.setDefaultValue(0).setValidator(
    function<bool (long)>([] (long value) {
      return value > 0;
    }));
```

The default value will not be validated against the validation function.  I *have not* tried doing this:

```cpp
  // cannot confirm if this has same behavior
  mySetting.setValidator(
    function<bool (long)>([] (long value) {
      return value > 0;
    })).setDefaultValue(0);
```

As to what should be done about this, I'm not sure; perhaps a warning or just documentation.  I could envision this being a valid use case.  For my use case, however, it's a programming error.

My Homie `HEAD` is bf7188e.

**Comment by marvinroger** [comment]
Would it be okay if we abort the code if the default setting is not valid?

**Comment by marvinroger** [comment]
Done!
