### ISSUE TITLE
reset remotely via mqtt

### ISSUE THREAD

**Issue by CWempe** [marvinroger/homie-esp8266#33]
How about a specific mqtt topic to reset the device remotely?

like:
devices/xXxXxXxX/$reset true
or
devices/15b638e0/$online/set true

**Comment by marvinroger** [comment]
Already done, see https://github.com/marvinroger/homie/blob/master/README.md#device-properties

**Comment by CWempe** [comment]
I admit, I did not see that. :)

But this does reset the configuration.
What I meant was just a reload/restart/reboot of the device.

**Comment by marvinroger** [comment]
If this is useful in the case of your sensor, you can implement it yourself easily (just create a node that you subscribe to a `restart` property). As you said, this would be useful to fix the openHAB behavior, and I don't see any other use cases to that. So once again, I am not in favor for implementing it. I hope you understand my point of view ;)

**Comment by CWempe** [comment]
I do understand.
Feel free to close these issues. :)
