### ISSUE TITLE
Different web configuration issues

### ISSUE THREAD

**Issue by luebbe** [marvinroger/homie-esp8266#333]
Trying to configure basic homie 2.0 example with http://setup.homie-esp8266.marvinroger.fr/

Devices:
* iPhone/iOS 10.3/Chrome and iPad/iOS 9.x/Chrome:
Can get through all the configuration steps, but there's an error when the configuration is saved on the device
* Galaxy Tab/Android 4.4/Chrome:
Can get through all the configuration steps and save to device, but cannot enter Float values e.g. 1.0. The input field is cleared, when the '.' is pressed.
* Laptop/Ubuntu 16.4/Chrome:
Works as expected.

**Comment by marvinroger** [comment]
Th first issue is a problem with Apple devices already reported here: https://github.com/marvinroger/homie-esp8266/issues/48

The second one is not our fault. The input is defined as `<input type="number" step="any" />`, so it accepts floating number. There's a bug in the browser!
