### ISSUE TITLE
Create tag 2.0.0-b1 ?

### ISSUE THREAD

**Issue by euphi** [marvinroger/homie-esp8266#338]
I'm using Homie-2.0.0 for a while and it runs very stable in various controllers.
It is also much more useful than 1.0.0 due to asynchronous MQTT, OTA etc.

I propose to tag the latest version of develop-branch with "2.0.0-b1" (or similar). This will create a "release" in githubs release-overview, and thgis it is made clear that Homie-2.0.0 is on its way to be released officially.

This also allows to access this version in other libraries, e.g. on platformio's library.json.

**Comment by marvinroger** [comment]
https://github.com/marvinroger/homie-esp8266/releases/tag/v2.0.0-beta.1 🎉
