### ISSUE TITLE
Firmware name length causes troubles

### ISSUE THREAD

**Issue by Denages** [marvinroger/homie-esp8266#339]
----UPDATED
**The reason was in the Arduino IDE 1.8.1-1.8.2 versions.**

Are there any restrictions to the firmware name length? If I set firmware name longer than 14 symbols I get truncated output while nodeMCU starts. 

**Example 1.** _Everything is OK:_

```
#include <Homie.h>

void setup() {
  Serial.begin(74880);
  Homie_setFirmware("uuuuurrrgggnnn", "1.0.0");
  Homie.setup();
}

void loop() {
  Homie.loop();
}
```
Result:
![homienobug](https://cloud.githubusercontent.com/assets/6689478/26483222/28340e2c-4216-11e7-93e8-86f67b372485.gif)

**Example 2.** _Getting output truncated. The longer firmware name is - the more output truncated._
```
#include <Homie.h>

void setup() {
  Serial.begin(74880);
  Homie_setFirmware("uuuuurrrgggnnnRRRRRR", "1.0.0");
  Homie.setup();
}

void loop() {
  Homie.loop();
}
```
Result:
![homiebug](https://cloud.githubusercontent.com/assets/6689478/26483190/f2697b10-4215-11e7-972e-fd3128d9db8d.gif)

Homie v.2.0.0, nodeMCU 1.0. Preloaded config:

```
{
  "name": "Hall_Bathroom_Manager",
  "device_id": "hall_bathroom_manager",
  "wifi": {
    "ssid": "Asgard",
    "password": "*******"
  },
  "mqtt": {
    "host": "192.168.88.250",
    "port": 1883,
    "base_topic": "homie/",
    "auth": true,
    "username": "admin",
    "password": "******"
  },
  "ota": {
    "enabled": true
  },
  "settings": {
    "percentage": 55
  }
}
```
----UPDATE-----
I've tried to reduce _name_ and _device_id_ in config and even with short firmware name I get this strange behavior:
Code:
```
...
  Homie_setFirmware("uuuuurrrgggnnn", "1.0.0");
...
```
Config:
```
{
  "name": "Hall_Bath_Sl",
  "device_id": "hall_bath_sl",
...
```
Result:
   
![homiebug2](https://cloud.githubusercontent.com/assets/6689478/26483631/3209fef0-4218-11e7-97c0-80eb08356820.gif)

Also I tried to erase flash with esptool:
`sudo python esptool.py --port /dev/cu.SLAB_USBtoUART erase_flash`
Then reflash and reconfigure. The same result.

After that every 60 seconds the status uptime messages appears normally

**Comment by benzino77** [comment]
You can find information about limits [here](https://github.com/marvinroger/homie-esp8266/blob/develop/src/Homie/Limits.hpp)

**Comment by Denages** [comment]
@benzino77 
Thanks. According to this I don't exceed limits.

**Comment by benzino77** [comment]
What model/kind of ESP are you using?

**Comment by Denages** [comment]
@benzino77 
nodeMCU 1.0

**Comment by benzino77** [comment]
On my side there was a problem with led feedback and reset button/trigger so I always do (before `Homie.setup()`):
```
...
Homie.disableLedFeedback();
Homie.disableResetTrigger();
...
Homie.setup()
```

**Comment by Denages** [comment]
Now I've tried to erase flash manually by uploading dummy zero-filled 4mb file. Then eased with esptool. Then I've updated library to the current Homie version from github....  Configured with son file and......The same result :(
Here is interesting moment. After the first status 60 sec message the truncated part is added to the output:
![homiebug3](https://cloud.githubusercontent.com/assets/6689478/26485061/a2a3cbee-421f-11e7-9e2a-b5237ca1095c.gif)

**Comment by benzino77** [comment]
Have you got other MCU (another board)? If so try with another one.

**Comment by Denages** [comment]
@benzino77 

> Also I tried to flash another just-unpacked nodeMCU module. The same result.

**Comment by benzino77** [comment]
What speed of the terminal have you set?

**Comment by Denages** [comment]
**I've found the problem.** Yesterday I updated Arduino IDE to 1.8.2 version.
Now I installed old 1.8.1 version and the issue gone!
After that I installed 1.8.2 again - the issue appeared again.
I even do not need to reflash nodeMCU.
P.S. v 1.8.1 has that bug too.

**Comment by marvinroger** [comment]
@Denages thanks for the report. I'll check, but it sounds weird!

**Comment by marvinroger** [comment]
I don't experience that issue. Let's say it was something wrong with your Arduino 1.8.x install.
