### ISSUE TITLE
question:How can I get the ID device

### ISSUE THREAD

**Issue by Eider3a** [marvinroger/homie-esp8266#349]
"Homie for ESP8266 has spawned a secure AP named Homie-xxxxxxxx. For example, if the AP is named Homie-c631f278, the AP password is c631f278. Connect to it.

Note: This c631f278 ID is unique to each device"

I want to get the ID code(c631f278) or some code unique for each device, I need to know wich device is sending data to a database.

Thank you.

**Comment by amayii0** [comment]
Looks like you can read about that from here:
https://github.com/marvinroger/homie-esp8266/blob/develop/src/Homie/Utils/DeviceId.hpp
https://github.com/marvinroger/homie-esp8266/blob/develop/src/Homie/Config.cpp#L320

Also second level of the MQTT topics is the client ID:
homie/6001940b97c8/temperature/degrees

**Comment by marvinroger** [comment]
See http://marvinroger.github.io/homie-esp8266/2.0.0-beta.1/advanced-usage/miscellaneous/
