### ISSUE TITLE
Documentation requested: Properties, Set and Advertise?

### ISSUE THREAD

**Issue by rekcodocker** [marvinroger/homie-esp8266#352]
I've read the documentation but I am missing something.  
What is the concept of a **property** - by which I mean: What is it intended use?  I would like to see the different class-methods documented with their intended use.

Specifically: what exactly is HomieNode.advertise for?

**Comment by marvinroger** [comment]
> **Getting started**
To use Homie for ESP8266, you will need:
> * To understand the [Homie convention](https://github.com/marvinroger/homie)

😉

**Comment by marvinroger** [comment]
The `advertise` method allows you to tell the framework that the node exposes the given property.
