### ISSUE TITLE
ESP 32 ?

### ISSUE THREAD

**Issue by timpur** [marvinroger/homie-esp8266#353]
Wondering if their is any plan to implement Homie on the esp32?

**Comment by marvinroger** [comment]
I'll see when the Arduino core for ESP32 is released and quite stable. 😉

**Comment by marvinroger** [comment]
But the code should not change too much, anyway.

**Comment by timpur** [comment]
Yeah thats why im investing into this platform, consistency... 
When the arduino core is stable im excited to start using the esp32 :)

Love the framework btw.

**Comment by timpur** [comment]
Any success with trying out the esp32 ?

**Comment by timpur** [comment]
Have you seen this?
https://github.com/me-no-dev/AsyncTCP

Wondering if we can spin up a repo for homie-esp32 to start porting homie to esp32?
Do you think most of the dependencies for homie on esp32 are there ?

**Comment by bertmelis** [comment]
The Ticker library is also missing. But that could be bypassed by using the "currentmillis-previousmillis"-approach.

**Comment by timpur** [comment]
Or we can port it also for esp32 (i think the community would like that)
