### ISSUE TITLE
[Wiki] how to upload config.json to SPIFFS

### ISSUE THREAD

**Issue by CWempe** [marvinroger/homie-esp8266#37]
As a newbie I don't know what SPIFFS is and how to upload a file to it. :(

I guess this might be the point to start:
https://github.com/esp8266/Arduino/blob/master/doc/filesystem.md#uploading-files-to-file-system

I would suggest to elaborate a little more about this in the wiki.
Or point to a good tutorial. :)

**Comment by marvinroger** [comment]
I can't point to other directions than the one you posted. I'll add a link on the Wiki! :)

**Comment by marvinroger** [comment]
Link added to the wiki.
