### ISSUE TITLE
serve an own URL

### ISSUE THREAD

**Issue by LarsES8266** [marvinroger/homie-esp8266#370]
how can it be done, to serve additional pages in webserver like

server.on("/states",xyz) ?

i would be nice, if you can give me a starting point ....

**Comment by marvinroger** [comment]
Unfortunately it is not and won't be possible "natively" in the framework. The webserver is only launched in configuration mode and the MQTT client is the only network entity started when in normal mode.

If you want a webserver in normal mode, you'll have to implement it yourself in your sketch. 😉
