### ISSUE TITLE
Use Serial1 as logging output

### ISSUE THREAD

**Issue by hgruber** [marvinroger/homie-esp8266#383]
For the H801 there's only UART1 available as serial interface. So I need to have my log on Serial1. I found no way to do this without code changes. It would be nice to have this possibility as well.

**Comment by benzino77** [comment]
http://marvinroger.github.io/homie-esp8266/2.0.0-beta.1/advanced-usage/logging/
(if you are using version develop or 2.0 beta)

**Comment by hgruber** [comment]
Thanks, it's working. My fault, should have seen it in the docs.
