### ISSUE TITLE
Project - HomieManagement

### ISSUE THREAD

**Issue by timpur** [marvinroger/homie-esp8266#418]
Hi community, ive been working on this in my spare time. Its a manager for Homie, based on v 2.0 and esp8266....

So far all it can do is view current device stats, change device config and flash firmware, all over mqtt.

Have a look, its a work in progress. Don't expect much.

[https://github.com/timpur/HomieManagement](https://github.com/timpur/HomieManagement)

**Comment by amayii0** [comment]
(bookmarked :) in todo list of things to check)

**Comment by marvinroger** [comment]
Oh, @timpur, feel free to add that to the https://github.com/marvinroger/homie/blob/redesign/implementations. 😉

**Comment by timpur** [comment]
yeah i think i will when i work on it a bit more and there arnt so many bugs :P (soon)
