### ISSUE TITLE
Homie@1.5.0 ArduinoJson dependency

### ISSUE THREAD

**Issue by Noxs** [marvinroger/homie-esp8266#422]
Hi,

For information, Homie@1.5.0 doesn't compile anymore with the ArduinoJson's version: 5.11.2, 5.11.1, 5.11.0.

Is the version 1.5.0 still maintained?

Thanks for your time.

**Comment by amayii0** [comment]
Relates to #361 / #362 / #363

**Comment by Noxs** [comment]
Thanks!
