### ISSUE TITLE
Question on code: online/offline

### ISSUE THREAD

**Issue by psyciknz** [marvinroger/homie-esp8266#423]
While not an issue, hoping someone can help.

How is the $online false set if not driven use user code.  Ie what sets the online state from true to false when the device has disconnected/lost power?  Can someone explain?  I'd like to replicate in code for something else, so it uses the homie model of showing is a device is connected.

It looks like the true status is set as a retained message to the $online topic with the QOS set to At Least once?  I just can't figure out how the broker knows the device has gone and sets the $online to false.

**Comment by n8twj** [comment]
Hi - I believe it has something to do with the "Last Will and Testament"
concept from MQTT, but I cannot quickly locate an example


Typos courtesy of my iPhone

**Comment by psyciknz** [comment]
I saw the posting of the true status in the boot-normal.cpp.   And it looked like it was retained.  The 1 before retained I thought was the at least once.

But I replicated that in c# and the true was set but it didn’t set to false when I exited.

_____________________________

**Comment by psyciknz** [comment]
Figured it out, you helped with the LWT guidance.  So for the client I was using, setting the last will and testament was part of the connection.  And you set the $online to false as LWT.

Then as part of connecting you create a $online true.  And so on disconnection (forcibly) the LWT takes effect.

Thanks, interesting exercise.
