### ISSUE TITLE
Not able to reset config

### ISSUE THREAD

**Issue by mishoboss** [marvinroger/homie-esp8266#431]
Hi guys,
I don't know if its a bug or its me unable to figure out how to reset config and boot ESP into configuration mode from normal mode.

Here's what I do:
- I have a dedicated button and I use a button library that calls events on buttons presses, hold, long holds, etc. So I don't use the `Homie.setResetTrigger()` function in setup.
- This button press just sets a boolean flag `resetFlag`
- This is my loop

```
  if(resetFlag){
    Homie.reset();
  }
  Homie.loop();
  ... other stuff in loop
  if(resetFlag){
    ESP.restart(); 
  }
```

The device restarts, but it doesn't boot in configuration mode. It is in normal mode and connects successfully to WiFi again. I tried some kund-fu with `Homie.setIdle(false/true)` but its still the same result. I'm using latest git code from yesterday, 18th Nov.

**Comment by bertmelis** [comment]
no need to call ESP.restart(). Homie wil do that for you afaik.

**Comment by mishoboss** [comment]
Well, it doesn't. :(

**Comment by mishoboss** [comment]
It works! Sorry about that. I removed the `ESP.restart(); ` and all works good now. Please remove this issue.
