### ISSUE TITLE
WIFI_CONNECTED does not get fired after a WiFi reconnect

### ISSUE THREAD

**Issue by T94T** [marvinroger/homie-esp8266#449]
Hi,
I use the latest version of homie-esp8266. When I turn on the device HomieEventType::WIFI_CONNECTED event gets fired. After turning off and on my WiFi router, this event does not get fired anymore. Is this a bug, or do I something wrong?

**Comment by timpur** [comment]
Hard to say 
How long do you leave your router off for ?

**Comment by T94T** [comment]
Just wanted to test the events. So I turned off the router and switched it back on immediately.

**Comment by T94T** [comment]
btw: The device reconnects to the WiFi AP but the event does not get fired.

**Comment by timpur** [comment]
Might not to do with homie more the the esp Arduino sdk

**Comment by T94T** [comment]
Thank you for this hint. Just made a git pull on esp8266/Arduino.

Even
`WiFi.isConnected()`
returns false after the device is reconnected. Very strange...

**Comment by T94T** [comment]
@marvinroger: Could this be the problem? https://github.com/esp8266/Arduino/issues/2735#issuecomment-264711139 How is your code implemented?

**Comment by T94T** [comment]
Problem seems to be solved with the latest master branch of esp8266/Arduino. Please have a look at this: https://github.com/esp8266/Arduino/issues/4161

**Comment by timpur** [comment]
Cool :)
