### ISSUE TITLE
Programmatically read device_id

### ISSUE THREAD

**Issue by T94T** [marvinroger/homie-esp8266#463]
Is it possible to read the config variable device_id by code?

**Comment by timpur** [comment]
in theory you can use this for now
`HomieInternals::Interface::get().getConfig().get().deviceId;`

**Comment by T94T** [comment]
Great! This works. Thanks a lot!

**Comment by timpur** [comment]
Yeah not the best method, ill add a cleaner method for you now.

**Comment by timpur** [comment]
forgot to add `Homie.getDeviceID()` is the new way in v2.1
