### ISSUE TITLE
Captive Portal Not Loading iPhone and Mac

### ISSUE THREAD

**Issue by BTopbas** [marvinroger/homie-esp8266#476]
Hello everyone. I am new with homie. I flashed basic code and flashed ui_bundle.gz to data/homie folder my esp8266. But in iPhone and Mac captive portal not loading. Here is the screenshoots.

<img src="https://user-images.githubusercontent.com/6390054/35385991-5733b918-01db-11e8-86aa-66bbfd6720c1.PNG" width="50%" height="50%">

When i go in safari go to 192.168.123.1 url i see this.

<img src="https://user-images.githubusercontent.com/6390054/35385990-56fd34ec-01db-11e8-8d05-eff1749a4d08.PNG" width="50%" height="50%">

When i go in google chrome go to 192.168.123.1 url i see this.

<img src="https://user-images.githubusercontent.com/6390054/35386479-4124f7ca-01dd-11e8-8e61-4beadd05f822.PNG" width="50%" height="50%">

And my macbook(HighSierra) connect esp8266 wifi, opens up captive portal but show nothing. Blank white.

Working only with google chrome on mac and enter manually 192.168.123.1 then i see config web page.

I erased my esp8266 flash and reupload ui_bundle but same happened.. Apple's system want to download this file. Only mac with google chrome showing as webpage.

**Comment by timpur** [comment]
Odd, will look into

**Comment by emil2099** [comment]
To add to this issue, I am getting: 

- Request not found for url: http://192.168.123.1 with Microsoft Edge 38.14393
- ui_bundle.gz download on all Apple devices (iPhone, iPad, MacBook)
- Everything works as expected on Chrome on Windows and MacOS

**Comment by rgriebl** [comment]
This is a well known Safari bug on all platforms: Safari can handle gzip compression perfectly fine - as long as the file extension is NOT ".gz". So simply renaming ui_bundle.gz to ui_bundle.htmlgz (plus adjusting CONFIG_UI_BUNDLE_PATH[] in Constants.hpp) fixes the problem. Just tested with iOS and macOS.

**Comment by timpur** [comment]
okay good to know, ill see if i can strip with file extension in homie as it responds
