### ISSUE TITLE
Describe CLI method for uploading configuration

### ISSUE THREAD

**Issue by AndrewDonaldson** [marvinroger/homie-esp8266#49]
I have been unable to upload a configuration with the Web UI / app and I don't own an android device.

I believe I should have been able to upload a configuration using curl, but so far I haven't had success. 

An example for doing this in the wiki would be appreciated. Then I could reduce the scope of what I am doing wrong.

I tried:
curl --upload-file config.json http://homie.config/config

which gives me {"success":false}, with a 400 error code.

github doesn't like me attaching the config file. I tried your complete example, simplified ones etc.

**Comment by marvinroger** [comment]
As mentionned in the API, you must send the data as `application/json`:

`curl -X PUT http://homie.config/config -d @config.json --header "Content-Type: application/json"`

Open the serial monitor, and you will see logs with the reason your request has been denied.

**Comment by rigorm** [comment]
If it helps, I use the "Chrome poster" extension under chrome to send the JSON info

I simply copy/pasted the JSON structure and changed what I needed then, click on "PUT".

just like the API page says: paste under http://homie.config/config

no need to upload a file :)

**Comment by marvinroger** [comment]
Thanks for the tip @rigorm ;)

**Comment by AndrewDonaldson** [comment]
Thank you, that worked. I see you added it to the documentation also.

**Comment by marvinroger** [comment]
You're welcome!
