### ISSUE TITLE
[Featurerequest] Restart/Reset without deleting configuration

### ISSUE THREAD

**Issue by JorinL** [marvinroger/homie-esp8266#491]
I have currently some problems with my local network and sometimes it brings up wrong hostnames or other things.

For this it would be helpful to not have to unplug my eps's from energy to restart them without clearing config.  How about "Homie.restart()" :-) ?

Is there possible yet a wayto do so? Or would it have to be constructed?

Could it be "ESP.restart();" ?

**Comment by timpur** [comment]
See #458 there is a add already to do this via mqtt and I believe via code (need to double check that )

**Comment by JorinL** [comment]
Ah cool!

**Comment by timpur** [comment]
Also homie.reboot() is there

**Comment by timpur** [comment]
This release is still a work in progress, but it you like you can use this branch for easily accessible just not it is not been stress tested, but seems stable in my and a couple of others testing. You can also add to this and give feedback if you decide to use it.

**Comment by JorinL** [comment]
Thanks for the Feedback :-)

**Comment by JorinL** [comment]
One more question -  homie.reboot()  bring @my side 'homie' was not declared in this scope.
Wrong branch :-D ?

I tried it now with:  2.2 and dev. Both seem to be wrong :-D

**Comment by luebbe** [comment]
capitalization?

**Comment by timpur** [comment]
by bad, Homie.reboot() ???

**Comment by JorinL** [comment]
Well simply yes........ Is there something somehow i should have know that? ;-D

Thanks for the help! I really searched for the cause.
