### ISSUE TITLE
Let the OTA server know which version was announced via MQTT

### ISSUE THREAD

**Issue by marvinroger** [marvinroger/homie-esp8266#50]
As asked by @rschaten on #35

**Comment by rschaten** [comment]
Thanks! :+1:

**Comment by marvinroger** [comment]
The new version string is `da828fe0=sub2-relay@1.0.0->1.1.0`.

* `da828fe0`: the device ID
* `sub2-relay`: the firmware name
* `1.0.0`: the firmware version
* `1.1.0`: the OTA version announced via MQTT

**Comment by marvinroger** [comment]
This will be released with 1.3.0 when the stabilty issues are resolved.

**Comment by jpmens** [comment]
Is there a particular reason you didn't opt for a single-character separator?

```
da828fe0=sub2-relay=1.0.0=1.1.0
```

That would make it a bit easier to _split_ on reception, wouldn't it?

**Comment by marvinroger** [comment]
Well yes, it's way easier to split with a single char. I don't know why I did this. :disappointed_relieved:  Fixed 2481bdfa60b0c8f686c927cfefe47f240229590d

**Comment by marvinroger** [comment]
Released. :)
