### ISSUE TITLE
Can I switch the status LED off? Wemos D1

### ISSUE THREAD

**Issue by maxlein** [marvinroger/homie-esp8266#514]
Hi,

is it possible to switch the status led off?
It seems there is every X seconds a short blue blink.
I have a Wemos D1 in bedroom, and even though the LED is so small, it's much too bright for bedroom.

cheers
Max

**Comment by timpur** [comment]
Please read the docs first

http://marvinroger.github.io/homie-esp8266/docs/develop/advanced-usage/built-in-led/
