### ISSUE TITLE
Request: Add persistence to items

### ISSUE THREAD

**Issue by rigorm** [marvinroger/homie-esp8266#53]
What I mean is, send the state of the items at a interval.

I'm seeing some weird actions with buttons on openHAB as, I would click them and they would revert back but the sensor would be in the asked state. so, by sending the states at a interval, the server would know the states.. (hope that i'm clear enough) :) # # @

**Comment by marvinroger** [comment]
This has been discussed before, I can't remember where, but this is an openHAB issue. One of the benefits of MQTT is to be able to send retained messages, so we don't have to send them at an interval as you say.

**Comment by rigorm** [comment]
Alright then.. I guess that the issue can be closed

**Comment by marvinroger** [comment]
Sorry! I'm sure you understand that we cannot fix the issues of every controllers on the market. ;)
