### ISSUE TITLE
"device_stats_interval": 900, ist not correct shown in mqtt - but works.

### ISSUE THREAD

**Issue by JorinL** [marvinroger/homie-esp8266#546]
Hey there, I tried to configure Homie that it sends out every 900 seconds the stats.

`{
  "name": "sonoff-s20-1",
  "device_id": "unicolor_rgb_strip_pc",
  "device_stats_interval": 900,
  "wifi": {
    "ssid": "XXXXXXXXXXXXXXX",
    "password": "XXXXXXXXXXXXXX"
  },
  "mqtt": {
    "host": "192.168.0.8",
    "port": 1883,
    "base_topic": "homeland/haushalt/elektrik/rgb/",
    "auth": true,
    "username": "XXXX",
    "password": "XXXXXXXXXXXXXXXXXXXXX"
  },
  "ota": {
    "enabled": true
  }
}`

Optical that leads to - but it is working:
> homeland/haushalt/elektrik/sonoff/sonoff-s20-1/$stats/interval 0

> homeland/haushalt/elektrik/sonoff/sonoff-s20-1/$stats/signal 100
homeland/haushalt/elektrik/sonoff/sonoff-s20-1/$stats/uptime 1803
homeland/haushalt/elektrik/sonoff/sonoff-s20-1/$stats/signal 100
homeland/haushalt/elektrik/sonoff/sonoff-s20-1/$stats/uptime 2703

**Comment by mwildbolz** [comment]
it is written as $stats/interval 0 because of the division by 1000, already reported as bug in #521

**Comment by JorinL** [comment]
Ah :-) fine!

**Comment by JorinL** [comment]
Duplicate of #521
