### ISSUE TITLE
Advertise device through mDNS and DNS-SD

### ISSUE THREAD

**Issue by marvinroger** [marvinroger/homie-esp8266#55]

**Comment by marvinroger** [comment]
Finally there is no need to: the device already advertise itself through the MQTT. So this would be a complete waste of resources.

**Comment by rigorm** [comment]
Actually, I would put this one on hold.. devices are advertised on the MQTT but i'm not sure that they will be discovered as such. finding this via wifi would make it more effective.. MQTT is more of a transport method.. understand what i mean ? ;)

**Comment by marvinroger** [comment]
Memory is precious, this is a waste of resources. Let me explain: if we make devices discoverable via mDNS, you can detect there is a device connected to the network and it's IP. Great. Then what? If you want to get other information about the device, or interact with it, you need to do it via MQTT anyway.

So simply, just subscribe to `devices/+/$online`, check if it equals to `true` and if yes, apply the regex `^devices\/([a-z0-9-]+)\/\$online$` to the topic, so you have the device ID in `$1` and you've just discovered all Homie devices. :smile:

**Comment by rigorm** [comment]
I agree on that point.. (did not know about the + un a MQTT subscribe string). 
I was looking into binding making on openhab2 and looks like you need predefined "things" switch, sensors, relay etc.. So i'm so sure this would be a good thing for your framework as you "thing" can virtually be anything a use defines. 

Bottom line, this stays closed :)

**Comment by qtronik** [comment]
Wow! Should put this trick in the readme file!

**Comment by marvinroger** [comment]
Good point! But where? In the Homie convention, or in the docs of this repo?
