### ISSUE TITLE
Wifi Reset -- if not connecting

### ISSUE THREAD

**Issue by fender21** [marvinroger/homie-esp8266#552]
If my device cannot connect to an exisiting wifi connection, how can I force a reset via code?  I do not have access to the actual switch/button so I want to allow the software to do this when a connection is down for more than a few tries?

**Comment by jmozmoz** [comment]
Have look at my project using Homie:
https://github.com/jmozmoz/yagds/blob/master/uploadSensorData/src/main.cpp

I use the SimpleTimer library to set a timeout for the Wifi connection: On a successful connection, the timer is deleted. If it "survives" it will send the ESP into deep sleep mode (you probably could also trigger a reset).

**Comment by fender21** [comment]
Thank you @jmozmoz !
