### ISSUE TITLE
Is imroy pubsubclient more reliable?

### ISSUE THREAD

**Issue by jpmens** [marvinroger/homie-esp8266#66]
Sorry to raise this question here, but I'm wondering whether somebody here knows if https://github.com/imroy/pubsubclient is maybe more reliable/stable than the orignal PubSubClient for ESP8266. I've seen some hiccups on ESP8266 and Homie (reported here earlier), and I'm wondering whether this library maybe fixes those?

**Comment by marvinroger** [comment]
I also asked for feedback on the openHAB forum, maybe you saw it. This is something I definitely consider, and I started to work on it by abstracting MQTT functions into the [MqttClient class](https://github.com/marvinroger/homie-esp8266/blob/master/src/Homie/MqttClient.cpp), so it will be a piece of cake to make the switch.

**Comment by marvinroger** [comment]
I will try to benchmark the two libraries, to monitor the times it takes to connect / subscribe / publish, how many times it reconnects, and how much memory it uses.

**Comment by jpmens** [comment]
FWIW, I've done a few tests with a simple sketch that subscribes to a single topic, prints the payload string to Serial: there's not much difference between the two libraries in terms of stability. I can fire off about 100 messages (qos=0, qos=1) and they _tend_ to arrive without resetting the device. Anything above that number quickly crashes the module.

On the other hand, if I attempt to publish what the device received (i.e. play "echo" server), things quickly fall apart: while PubSubClient manages to echo two or three messages, the _imroy_ version just quietly dies.

This is meant as a heads-up, that it's probably not worth your while to pursue the modularization, so please close this asap. :-)

**Comment by marvinroger** [comment]
Alright, thanks for testing! I will try to learn more about the MQTT network protocol, and attempt to implement something with the [ESPAsyncTCP](https://github.com/me-no-dev/ESPAsyncTCP) library. As it is non-blocking, it might handle a lot more workload and therefore be more stable. However, there is not support for SSL for now (https://github.com/me-no-dev/ESPAsyncTCP/issues/9).

**Comment by jpmens** [comment]
Well, to be honest, within a closed environment, TLS is probably overrated anyway. 😆 

/me _ducks_

**Comment by jpmens** [comment]
@marvinroger You should speak to @ckrey about this: he's our MQTT protocol guru. Honestly: he built OwnTracks for iOS and has done tons of MQTT protocol tests with different brokers. I'll ask him to create a repo to start working on this with you.

**Comment by jpmens** [comment]
https://github.com/ckrey/mqtt-esp

**Comment by marvinroger** [comment]
I can't work on this right now, I have my exams soons so I'll have to slow down. :confused:

**Comment by Jorgen-VikingGod** [comment]
I had some issues in the past with pubsubclient and 10+ retained messages.
After connection all the messages are bombed into my ESP8266 and forces sometimes a crash.
To avoid this, I added a ring buffer and push all arrived messages (ok maybe not all ;) )
In my loop I process/pop all stored messages.
This is working really stable for me by the way

**Comment by marvinroger** [comment]
Here is the asynchronous library I've been working on this week-end: [marvinroger/async-mqtt-client](https://github.com/marvinroger/async-mqtt-client). It seems pretty stable, but some exceptions seem to appear on disconnect... It would help a lot if I can have feedback on it. :smiley:

**Comment by marvinroger** [comment]
AsyncMqttClient will be used, see https://github.com/marvinroger/homie-esp8266/issues/87
