### ISSUE TITLE
Configuration Site http://marvinroger.github.io/homie-esp8266/ broken!?

### ISSUE THREAD

**Issue by euphi** [marvinroger/homie-esp8266#85]
I cannot configure my device using http://marvinroger.github.io/homie-esp8266/ . Whenever I connect to my ESP8266 the page shows the configured nodes, but it is not possible to move to the next page (The small icon on top changes to next, but browser still shows the info page.

`
Triggering Wi-Fi scan...
✔ Wi-Fi scan completed
Triggering Wi-Fi scan...
✔ Wi-Fi scan completed
Triggering Wi-Fi scan...
✔ Wi-Fi scan completed
Received heart request
Received device info request
`

**Comment by marvinroger** [comment]
You're right, I tried to reduce the size of configuration UI to be able to embed it into the device itself, and I broke everything!

**Comment by marvinroger** [comment]
Can you try again?

**Comment by euphi** [comment]
Yes, works fine now. Many thanks!

**Comment by marvinroger** [comment]
You're welcome!
